### ISSUE TITLE
每个都需要手动创建somoView问题

### ISSUE THREAD

**Issue by kikao123** [OpenFeyn/Somo#6]
我写了个UITableViewCell分类,动态添加了somoSkeletonLayout方法,里面对cell的contentView的subviews进行遍历,如果是label,imageview就创建somoView,并把frame赋值给它,imageview额外判断下cornerRadius,如果cornerRadius>0,就把值附给somoView,然后如果需要展示somoView的tableView,就把代理指向下SomoDataSourceProvider,这样解决有问题吗?你还有更好的方法解决手动创建somoView问题嘛?谢谢啦

**Comment by OpenFeyn** [comment]
没有更好的思路。这个库在我看来并不那么友好。仅仅是给同事使用时随便想的一段。
应该有更好的开源库，现在实在太忙。如果稍微空闲了。我会完善这个库。
